### PR TITLE
Some additions

### PR DESCRIPTION
**Pull request by isaacseymour**
== Simple ones: ==
- PositronicRelativeLayout
- PositronicExpandableListView

There's also PositronicSeekBar which breaks the OnSeekBarChangeListener up into its constituent functions and allows each one to be set by a nice onProgressChange(f : (Int, Boolean) => Unit) etc. Perhaps onProgressChange ought to be overloaded so the fromUser parameter is optional...?

I've also changed orm.RecordId.equals so that unsaved IDs on the same RecordManager equate. I think this is sensible as if you have a sometimes-null foreign key, then unsaved IDs are used as type-safe null values, so this makes null == null. On the other hand, if it's an actual on-table ID then the records are not equal, but in that case they both have null-ish IDs, so it's stupid to compare records by comparing IDs. Still, I'll leave it up to you as to whether or not you keep that change.

The only other change I've made that you haven't made yourself on the main branch is moving to Scala 2.9.2, and sbt 0.11.3, but I've only done that because I'm building against it for everything else.

### CODE REVIEW

**Comment by rst** [comment]
Thanks.  I'll grab the UI components (PositronicGridView, PositronicSeekBar, PositronicRelativeLayout, and and removeFromParent) and merge sometime this week, and probably the platform updates as well (2.9.2, though platformName in android is already android-14).  

It's a bit awkward to do an automatic merge here, for two reasons.  First, some of the commits look a bit ragged.  (I'm not sure what's going on with 4c4f74f, which seems to delete a few files.)

Second, I see how it's a bug that two records with null FKs don't compare equal, but I'm not sure you've got the right fix.  The way I read the code, it also makes IDs for all _unsaved_ records compare equal, which is something the code is deliberately set up to prevent right now.  It might be better to add a new "isNullId" state to the records, and have any with that compare equal.

(The reasoning here is that I want you to be able to, say, create an unsaved TodoList, and TodoItems referencing that TodoList, and then save the lot and have things work approximately right.  If that works, it should _also_ work to have two unsaved TodoLists, each with a set of associated TodoItems, and then save only one of them.  And for _that_ to work, the TodoItems must refer to particular unsaved TodoLists, not just "something unsaved".)

Anyway, I will grab at least the UI changes quite soon, and think about the other stuff.  Thanks!

**Comment by isaacseymour** [comment]
I wouldn't recommend adding removeFromParent - it's something I added a while ago but have removed because its behaviour isn't well-defined. Calling it on something without a parent just does nothing, or calling it on null equally causes no error. I think it's a false convenience - chances are you're going to end up calling it on something without a parent by accident and spending half an hour trying to work out why the hell that view is sticking around.

android-14/15: Yep - I only left those changes in this request because I'm useless with Git, as you have noticed...apologies.

Humm, yes I see that problem. That would require adding a static RecordId[T].nullId (or BaseRecordManager[T].nullId?) method to have as the default for the ManagedRecords, which is probably a good idea anyway for code clarity if nothing else (ie, compulsory FKs default to unsavedId, optional ones nullId which might prevent the odd SQLite constraint exception).

**Comment by rst** [comment]
UI widgetry now on trunk, I believe.  Now to figure out what to do about the isNull business...

**Comment by rst** [comment]
I've coded up the approach to handling null record IDs outlined above, and that's now on github as an experimental branch ("nullRecordIds").  I'm a bit hesitant about putting it on master, though, until I figure out how this plays with nullable columns of other types. 

 (The idiomatic Scala way of handling that situation would be to map those columns to fields declared as Option[T], which would get populated with None or Some(whatever) as the underlying column was null or not-null.  However, that would make it a lot more awkward, in Scala 2.9 and earlier at least, to infer the mappings between columns and fields at run-time, as all option types look alike at run-time.  I suppose I could work off the types declared in the database, and just assume that the user did the right thing when declaring the class, but that's also ... ugly.  There is some hope that the improved reflection in Scala 2.10 will make this easier to deal with --- if it works at all on Dalvik...)

At any rate, I think that closes up the issues raised in this pull request; I'm thinking about closing it, and maybe opening a new one for the null-ID business...

**Comment by isaacseymour** [comment]
I think that's probably best, the useful stuff from this request is all there.

Are you saying that Option[T] looks the same as Option[S]?! How ridiculous. Well perhaps we could just add a method to the RecordId class (along the lines of Seq.head/Seq.headOption):

``` scala
def fetchOption : Option[T] = this.fetchOnThisThread match {
  case null => None
  case _ => Some(_)
}
```

(although I've had problems doing matches like this, so it might have to be an if-else...?)

Anyway, I've closed this request...good luck with deciding how to deal with the null stuff!

**Comment by rst** [comment]
On Option[T] degrading to Option[_] at runtime --- yep.  It's a property of the JVM called "erasure" which Scala, as of 2.9, hasn't yet tried to do anything about.  2.10 may improve matters somewhat.

However, the RecordId class is not where the problem is.  It's instead in the internal stuff that tries to "intuit" the mapping between fields and db columns, so you don't need an explicit 'mapField' for every column in the record manager constructor/class declaration.  Right now, it looks for similarly-named and appropriately-typed fields and columns (switching naming conventions); if the field is declared as, say, Option[String], and the 'String' part isn't available at runtime, it doesn't have enough information to do that.

**Pull request closed without merging**
